name: Docker Build and Publish

on:
  push:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t flask-todo:${{ github.sha }} ./day36-flask-todo
