name: Hello workflow

on: push

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello from GitHub Actions"

      - name: Date and time
        uses: date
      
      - name: Name of branch
        uses: echo "Name of this branch is ${{ github.ref_name }}"

      - name: Runner's OS
        uses: cat /etc/os-release
      
      - name: Runner's OS 2
        uses: echo "OS of runner is ${{ runner.os }}""