name: Hello workflow

on: push

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello from GitHub Actions"

      - name: Date and time
        run: date

      - name: Name of branch
        run: echo "Name of this branch is ${{ github.ref_name }}"

      - name: List files in repo
        run: ls -la

      - name: Runner's OS
        run: echo "OS of runner is ${{ runner.os }}"